### ISSUE TITLE
Whitebox.invokeConstructor should support null

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#206]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 16, 2009 16:01:14_

It should be possible to supply a null value as parameter type to
invokeConstructor

_Original issue: http://code.google.com/p/powermock/issues/detail?id=186_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 22, 2010 02:18:22_

**Labels:** -Milestone-Release1.4 Milestone-Release1.5

**Comment by johanhaleby** [comment]
_From [betlista@gmail.com](https://code.google.com/u/betlista@gmail.com/) on December 28, 2012 01:56:28_

Same should work for invokeMethod, instead of

    invokeMethod( object, "method", new Object[0] )

I'd like to call

    invokeMethod( object, "method", null )

Yes, I know, that I can call

    invokeMethod( object, "method" )

**Comment by thekingnothing** [comment]
It's imposible to implement without changing API, because in case : 

public static <T> T invokeConstructor(Class<T> classThatContainsTheConstructorToTest, Object... arguments)
`invokeConstructor( object, "method", null )`
the method 
`public static <T> T invokeConstructor(Class<T> classThatContainsTheConstructorToTest, Object... arguments)` is called.
