### ISSUE TITLE
Legacy artifact download link broken

### ISSUE THREAD

**Issue by conorgdalyoj** [jayway/powermock#576]
The main download link for downloading older versions of PowerMock on [1] points to [2] which redirects back to this repo's github homepage.

[1]
Bottom of page - titled Legacy
https://github.com/jayway/powermock/wiki/Downloads

[2]https://code.google.com/p/powermock/downloads/list?can=1&q=&colspec=Filename+Summary+Uploaded+ReleaseDate+Size+DownloadCount

**Comment by johanhaleby** [comment]
Thanks for the reporting. I'm actually aware of this but I'm not sure how to solve it without reopening the old Google Code project. The problem is that once I closed the Google Code project it seems like ALL requests are redirected to the GitHub page (even the ones to the binary files). So the only option afaik is to open the Google Code project again. This might not be a huge problem though since we could clearly indicate the project has moved (and include a link to the github project). But I find it kind of nice that Google Code automatically redirects to the GitHub page.. But maybe not nice enough to make all old binary files unavailable. I'm also a bit scared the Google Code will remove all files in the future when they are shutting down the service for real. I should probably move all legacy files to bintray but that's (probably) a boring and time consuming job and I'm not looking forward to it :) Do you think I should at least reopen the Google Code project?

**Comment by conorgdalyoj** [comment]
At the risk of delaying migration even further, I think it should be re-opened. The only alternative to finding historic releases that I could find was http://mvnrepository.com/ and that's not the easiest site to get a specific release version alongside all with its dependencies.
GitHub again supports binary artifacts with "Releases"[1]. They also provide an API to interact with it.[2]
At a quick glance, the API seems a bit cleaner than BinTrays[3]:

[1] https://help.github.com/articles/about-releases/
[2] https://developer.github.com/v3/repos/releases/#create-a-release
[3] https://bintray.com/docs/api/

**Comment by johanhaleby** [comment]
Ok I've reopened it now. Thanks for your comments.

**Comment by geekrumper** [comment]
I stumbeld upon this issue and thought it's closed due a resolution. It proves that I was clearly wrong:
The docs still suggest the google code repo, which is closed. And here (github) are no links for legacy versions.
We are still using EasyMock 3.3.1 and not planing to update in the near future. I've tried to download it from maven, but as @conorgdalyoj mentioned, it's rather annoying to get all deps together for PowerMock alone... by putting all pieces (modules, reflect, core, api [easymock]) together, I wasn't able to even annotate "@RunWith()" correctly.

Any other ideas how I can get 1.6.0?

Thanks in advance for the help.

**Comment by thekingnothing** [comment]
@geekrumper, PowerMock 1.6.0 you may find on Bintray https://bintray.com/johanhaleby/generic/powermock/1.6.0

**Comment by geekrumper** [comment]
Thanks @thekingnothing...
