### ISSUE TITLE
PowerMock is not working with ByteBuddy

### ISSUE THREAD

**Issue by juherr** [jayway/powermock#579]
Related to raphw/byte-buddy#54

It may be a problem too when mockito/mockito#123 will be closed and if PowerMock  try to support the new major release.

**Comment by johanhaleby** [comment]
What do you mean by working? Are you trying to use PowerMock without Javassist?

**Comment by juherr** [comment]
Have a look to raphw/byte-buddy#54 and [the gist I gave](https://gist.github.com/juherr/69b3f7604f03c1946207).

Something fails when I mix usage of PowerMock and ByteBuddy.
@raphw analysed the issue (https://github.com/raphw/byte-buddy/issues/54#issuecomment-136959933)

**Comment by johanhaleby** [comment]
Hmm not sure if there's anything I can do, it might be out of my control. PowerMock is using Javassist and it might not work nice together with ByteBuddy? In that case perhaps you should file an issue for Javassist as well?

**Comment by juherr** [comment]
I propose we wait a @raphw comment because I don't understand the problem and I'm not really the one who can explain it... :/

**Comment by raphw** [comment]
The problem really is that the MockClassLoader does not provide a reference to the mock class it loaded. (See the example I provided that does not use Byte Buddy.)

When Byte Buddy loads its class, the normal class loading mechanism starts where Java resolves all direct references of the class. Among other things, it resolves the class's direct super class which is the class generated by PowerMock.

Byte Buddy's class loader queries its parent class loader for this class which is the MockClassLoader. But this class loader now claims that it does not know the Mocking class, despite it being loaded by this class loader before (violates the class loader contract, this is the actual bug).

As a result, the class loader now delegates to Byte Buddy's class loader for locating the power mock class which it does not know of course. Since the top of the class loader hierarchy is now reached, Byte Buddy throws a ClassNotFoundException as it is specified.

**Comment by rspython** [comment]
would this make its root cause the same as this bug then?  (which also has a suggestion on how to fix it?)
https://github.com/jayway/powermock/issues/564

**Comment by raphw** [comment]
No, the problem is slightly different. The problem JaCoCo faces is that the class's context is changed. The problem that Byte Buddy faces is that any class loader must preserve:

clazz.getClassLoader().findClass(clazz.getName()) == clazz

This is required for any class loader to fullfil its contract.

**Comment by johanhaleby** [comment]
Just to make it clear to me, there's indeed something I can do about this in PowerMock? I should make changes in MockClassLoader so that `clazz.getClassLoader().findClass(clazz.getName()) == clazz` evaluates to true?

**Comment by raphw** [comment]
Yes. If this would work, Byte Buddy could query its parent's class loader and everything would work as expected.

**Comment by johanhaleby** [comment]
Would it be enough to reproduce it if I create a new classloader that has MockClassloader as parent?

**Comment by raphw** [comment]
Yes, absolutely. Must be true for **any** class, though. Also, it must allow a parent pass-through, i.e.

mockClassLoader.findClass("java.lang.String") == String.class

**Comment by johanhaleby** [comment]
> Also, it must allow a parent pass-through

Does "parent pass-through" have anything to do with classloader priority? I.e. if you're using parent first or parent last? Because MockClassloader (if I remember it correctly) is using parent last.

**Comment by raphw** [comment]
Parent-last is all right, it must only be guaranteed that a class that the mock class loader's parent does know is not resulting in a class mot found exception. It is however okay to return another class.

Ill test your changes tomorrow!

**Comment by raphw** [comment]
Test runs green now.

**Comment by johanhaleby** [comment]
Thanks for trying it out
