### ISSUE TITLE
Problems using swing with PowerMockRunner

### ISSUE THREAD

**Issue by malinkallen** [jayway/powermock#651]
When trying to instantiate a swing component in a test class run with PowerMockRunner, I get a VerifyError in swing.UIManager, see the trace in the attached file. I use powermock-mockito-junit-1.6.3.

I'm running Java 8 on Ubuntu 15.10 and I use Eclipse to write and run my code. 

To reproduce the problem, this class can be used:

```
import javax.swing.JFrame;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
public class SwingClassloaderTest {
    @Test
    public void test() {
        JFrame frame = new JFrame();
    }
}

```

[VerifyErrorTrace.txt](https://github.com/jayway/powermock/files/190863/VerifyErrorTrace.txt)

**Comment by kohanian** [comment]
I'm getting the exact same problem. Have you figured it out by any chance?

**Comment by malinkallen** [comment]
Unfortunately not. :( I think this is a bug in Powermockito.

One workaround is to defer loading of the swing classes (using the annotation @PowermockIgnore), but then you cannot do PrepareForTest on swing components.

**Comment by thekingnothing** [comment]
I didn't have experience with Swing, but issue looks the same as with another framework which either uses custom classloader or work only with system class loader or work in another thread than test classes. 

Root clause: PowerMock loads classes by using custom class loader which modified classes during loading, but Swing doesn't know nothing about this class loader. I don't know if it possible to force Swing use custom class loader. 

From PowerMock side it's hard to fix the issue, because PowerMock should be aware that a test is run with some framework which requires special initialisation. As in this case.

**Comment by malinkallen** [comment]
@kohanian There is a [workaround](http://stackoverflow.com/questions/11943703/trying-to-mock-static-system-class-with-powermock-gives-verifyerror). (Applying this workaround, I get a LinkageError instead, but it seems to be a [known issue](https://github.com/jayway/powermock/issues/453).)
