### ISSUE TITLE
Cannot deploy powermock with maven

### ISSUE THREAD

**Issue by fainalex** [jayway/powermock#672]
Hi,

I want to use the last version of the powermock library (1.6.5) through Maven. But My package cannot be compiled, since Maven finds dependency Convergence error. Below you can see that there are 2 different versions of org.objenesis:objenesis library in the same dependency:

Dependency convergence error for `org.objenesis:objenesis:2.1` paths to 

```
dependency are:
+-mypackage:v1-SNAPSHOT
  +-org.powermock:powermock-api-mockito:1.6.5
    +-org.mockito:mockito-core:1.10.19
      +-org.objenesis:objenesis:2.1
and
+-mypackage:v1-SNAPSHOT
  +-org.powermock:powermock-api-mockito:1.6.5
    +-org.powermock:powermock-api-mockito-common:1.6.5
      +-org.powermock:powermock-api-support:1.6.5
        +-org.powermock:powermock-reflect:1.6.5
          +-org.objenesis:objenesis:2.2
```
I tried to make an exclusion, but I cannot exclude only one version, I need to exclude all of them, which does not pass me, as I think.

Did you have the same problem? What can I do?

(my issue copied from [here](http://stackoverflow.com/questions/37463356/dependency-convergence-error-for-powermock))

**Comment by thekingnothing** [comment]
There two different version of `objenesis`, because two different libraries depends on two different version of `objenesis`: PowerMock and Mockito. You have two options to resolve the issue: 

 - Exclude `org.objenesis:objenesis` from PowerMock dependencies and add it manually to your pom.
 - Exclude `mockito-core` from PowerMock dependencies and add it as separated decency to your pom with excluding `objenesis`.

**Comment by fainalex** [comment]
it's beautiful, thank you.
but it is still the bug, so i cannot understand, why you have closed it.

**Comment by thekingnothing** [comment]
I closed it, because it's not a defect. 
We cannot manage the dependency of 3rd party library. Even if we make mockito as provided dependency, the mockito should be added as dependency and again you will have two different version of `org.objenesis:objenesis`.
Mockito with version 1.10+ is not supported anymore, but PowerMock is supported and we try to use latest version of libraries.

**Comment by fainalex** [comment]
it IS still a bug of you maven project since your maven project can not be compiled with maven.

**Comment by thekingnothing** [comment]
As you may see on [travis](https://travis-ci.org/jayway/powermock)  - project can be compiled without any issues. PowerMock doesn't have any build issue.
