### ISSUE TITLE
powermock searches only for "java." when checking if type is java system class

### ISSUE THREAD

**Issue by michbeck100** [jayway/powermock#688]
When mocking e.g. javax.security.auth.Subject powermock (in conjunction with mockito) throws an exception, that it cannot mock final classes. 
As https://www.jayway.com/2009/05/17/mocking-static-methods-in-java-system-classes/ states powermock will create a new class at runtime with the same structure and create a mock of that class instead. This works only for classes of the package "java.*", as you can see in https://github.com/jayway/powermock/blob/master/api/mockito/src/main/java/org/powermock/api/mockito/internal/mockcreation/MockCreator.java#L93.

But what about the "javax.*" package?

**Comment by thekingnothing** [comment]
Thank you for report! I'll fix the pattern

**Comment by thekingnothing** [comment]
I've check and everything works fine without changing pattern, because classes from `java.*` could be loaded with PowerMock class loader. I added the test for your case: https://github.com/jayway/powermock/blob/master/modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/bugs/github668/GitHub668Test.java
