### ISSUE TITLE
AbstractMethodError when used with Mockito 2.1.0

### ISSUE THREAD

**Issue by kzaikin** [jayway/powermock#700]
When I try to use PowerMockito (the latest available 1.6.5) alongside Mockito 2.1.0 I get an exception in every test run even if tests do not use PowerMockito.

`java.lang.AbstractMethodError: org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.isTypeMockable(Ljava/lang/Class;)Lorg/mockito/plugins/MockMaker$TypeMockability;
`

This issue has been post to Mockito's github and it is clear PowerMockito has not adopted the latest Mockito changed yet.
https://github.com/mockito/mockito/issues/292

The same issue is asked at StackOverflow:
http://stackoverflow.com/questions/31685267/error-initializing-mockito-everytime-and-for-any-test-cases

Observed behavior: AbstractMethodError
Desired behavior: no error

**Comment by thekingnothing** [comment]
PowerMock will work with any version of Mockito higher than 2.0.42-beta.

**Comment by xdgimf** [comment]
Note that Mockito2 support is currently experimental
Mockito 2 is in beta stage and very quickly changing, so we cannot guarantee that PowerMock will work with any version of Mockito higher than 2.0.42-beta.

Found it here: `https://github.com/jayway/powermock/wiki/Mockito2_maven`

**Comment by kzaikin** [comment]
Mockito 2.1.0 is released which is not a beta. Wiki should be updated

**Comment by thekingnothing** [comment]
I updated wiki.

**Comment by Jacksgong** [comment]
Hi @thekingnothing , Thanks for your awesome work!

I also occur such problem, I use Mockito release version 2.1.0 and the PowerMock latest release version 1.6.6, this problem is still exist.

I use Mockito 2.1.0, because I write the unite-test for Kotlin. 

---

I comment in this issue, because I find this issue is the best match my problem, but it is marked as `duplicate` one, but I still can't find any resolution...

---

Thanks so much, look forward for your response!
