### ISSUE TITLE
Powermockito: withAnyArguments

### ISSUE THREAD

**Issue by MarkusS75** [jayway/powermock#716]
Hello,

when moving from version 1.6.5 to 1.6.6 all tests fail which are using the withAnyArguments inside of "whenNew". Proxy objects aren't created any more and stay null which results in NullPointerExceptions.

Rgds,
Markus

**Comment by thekingnothing** [comment]
Thank you for reporting an issue! 
Could you provide more information about environment and some code snippet to reproduce the issue. 
I'm asking, because we have [test](https://github.com/jayway/powermock/blob/master/modules/module-test/mockito/junit4/src/test/java/samples/powermockito/junit4/whennew/WhenNewCases.java) which checked `whenNew(...). withAnyArguments()` 
So I need more information to reproduce the issue.

**Comment by MarkusS75** [comment]
See attached zip with complete test scenario. if you run MyServiceTest with 1.6.5 it succeeds - with 1.6.6 it fails
[Test.zip](https://github.com/jayway/powermock/files/580434/Test.zip)
